spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MovieBookingApplication
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update   # Be careful in production
    show-sql: true

jwt:
  secret: 3df7#9kd^X@pL!m4Vr8eWzq1TbRuYc6FjK2HpLo9SaBvNmXt
  expiration: 3600000
